language C.UTF-8

set viminfo+=n~/.vim/viminfo

filetype plugin indent on

syntax on

" Copy indent from current line when starting a new line
set autoindent

" List of screen columns that are highlighted
set colorcolumn=81

" Highlight the screen line of the cursor
set cursorline

" Use the appropriate number of spaces to insert a <Tab>
set expandtab

" When there is a previous search pattern, highlight all its matches.
set hlsearch

" Ignore case in search patterns
set ignorecase

" While typing a search command, show where the pattern, as it was typed so far,
" matches. The matched string is highlighted
set incsearch

" The value of this option influences when the last window will have a status
" line:
"		0: never
"		1: only if there are at least two windows
"		2: always
set laststatus=2

" If the 'wrap' option is off, long lines will not wrap
set nowrap

" Show the line number relative to the line with the cursor in front of each
" line
set relativenumber

" Number of spaces to use for each step of (auto)indent
set shiftwidth=2

" Show (partial) command in the last line of the screen
set showcmd

" When a bracket is inserted, briefly jump to the matching one
set showmatch

" If in Insert, Replace or Visual mode put a message on the last line
set showmode

" Override the 'ignorecase' option if the search pattern contains upper case
" characters
set smartcase

" Number of spaces that a <Tab> counts for while performing editing operations
set softtabstop=2

" Number of spaces that a <Tab> in the file counts for
set tabstop=2

" Yank and paste the selection without prepending "* to commands
set clipboard^=unnamed,unnamedplus

highlight TrailingWhiteSpace ctermbg=red guibg=red
match TrailingWhiteSpace /\s\+$/

