font=IBM VGA Nerd Font Mono:size=16
font-bold=IBM VGA Nerd Font Mono:size=16
bold-text-in-bright=yes
pad=5x5 center-when-maximized-and-fullscreen

[url]
launch=firefox ${url}
style=single

[cursor]
blink=yes

[mouse]
hide-when-typing=yes

[colors-dark]
background=000000
foreground=aaaaaa
flash=aaaaaa
flash-alpha=1

## Normal/regular colors (color palette 0-7)
regular0=000000  # black
regular1=aa0000  # red
regular2=00aa00  # green
regular3=aa5500  # yellow
regular4=0000aa  # blue
regular5=aa00aa  # magenta
regular6=00aaaa  # cyan
regular7=aaaaaa  # white

## Bright colors (color palette 8-15)
bright0=555555   # bright black
bright1=ff5555   # bright red
bright2=55ff55   # bright green
bright3=ffff55   # bright yellow
bright4=5555ff   # bright blue
bright5=ff55ff   # bright magenta
bright6=55ffff   # bright cyan
bright7=ffffff   # bright white

## Misc colors
selection-foreground=000000
selection-background=aaaaaa
jump-labels=000000 00aaaa                    # black-on-cyan
scrollback-indicator=000000 aaaaaa           # black-on-white
search-box-no-match=aaaaaa aa0000            # white-on-red
search-box-match=000000 aaaaaa               # black-on-white
urls=00aaaa

[key-bindings]
# scrollback-up-page=Shift+Page_Up Shift+KP_Page_Up
# scrollback-up-half-page=none
# scrollback-up-line=none
# scrollback-down-page=Shift+Page_Down Shift+KP_Page_Down
# scrollback-down-half-page=none
# scrollback-down-line=none
# scrollback-home=none
# scrollback-end=none
# clipboard-copy=Control+Shift+c XF86Copy
# clipboard-paste=Control+Shift+v XF86Paste
primary-paste=none
search-start=Mod4+slash
# font-increase=Control+plus Control+equal Control+KP_Add
# font-decrease=Control+minus Control+KP_Subtract
# font-reset=Control+0 Control+KP_0
spawn-terminal=none
# minimize=none
# maximize=none
# fullscreen=none
# pipe-visible=[sh -c "xurls | fuzzel | xargs -r firefox"] none
# pipe-scrollback=[sh -c "xurls | fuzzel | xargs -r firefox"] none
# pipe-selected=[xargs -r firefox] none
# pipe-command-output=[wl-copy] none # Copy last command's output to the clipboard
show-urls-launch=Mod4+h
# show-urls-copy=none
# show-urls-persistent=none
prompt-prev=none
prompt-next=none
unicode-input=none
# color-theme-switch-1=none
# color-theme-switch-2=none
# color-theme-toggle=none
# noop=none
# quit=none

[search-bindings]
cancel=Escape
# commit=Return KP_Enter
find-prev=Control+p
find-next=Control+n
cursor-left=Left
cursor-left-word=Control+Left
cursor-right=Right
cursor-right-word=Control+Right
cursor-home=Home
cursor-end=End
# delete-prev=BackSpace
delete-prev-word=none
# delete-next=Delete
delete-next-word=none
delete-to-start=none
delete-to-end=none
extend-char=none
extend-to-word-boundary=none
extend-to-next-whitespace=none
extend-line-down=none
extend-backward-char=none
extend-backward-to-word-boundary=none
# extend-backward-to-next-whitespace=none
extend-line-up=none
clipboard-paste=Control+Shift+v XF86Paste
primary-paste=none
# unicode-input=none
# scrollback-up-page=Shift+Page_Up Shift+KP_Page_Up
# scrollback-up-half-page=none
scrollback-up-line=Shift+Up
# scrollback-down-page=Shift+Page_Down Shift+KP_Page_Down
# scrollback-down-half-page=none
scrollback-down-line=Shift+Down
scrollback-home=Shift+Home
scrollback-end=Shift+End

[url-bindings]
cancel=Escape
toggle-url-visible=none

[text-bindings]
# \x03=Mod4+c  # Map Super+c -> Ctrl+c

[mouse-bindings]
# scrollback-up-mouse=BTN_WHEEL_BACK
# scrollback-down-mouse=BTN_WHEEL_FORWARD
# font-increase=Control+BTN_WHEEL_BACK
# font-decrease=Control+BTN_WHEEL_FORWARD
# selection-override-modifiers=Shift
# primary-paste=BTN_MIDDLE
# select-begin=BTN_LEFT
# select-begin-block=Control+BTN_LEFT
# select-extend=BTN_RIGHT
# select-extend-character-wise=Control+BTN_RIGHT
# select-word=BTN_LEFT-2
# select-word-whitespace=Control+BTN_LEFT-2
# select-quote = BTN_LEFT-3
# select-row=BTN_LEFT-4

# vim: ft=dosini
