export XDG_CACHE_HOME="${HOME}/.cache"
export XDG_CONFIG_DIRS='/etc/xdg'
export XDG_CONFIG_HOME="${HOME}/.config"
export XDG_DATA_DIRS='/usr/local/share:/usr/share'
export XDG_DATA_HOME="${HOME}/.local/share"
export XDG_STATE_HOME="${HOME}/.local/state"
export EDITOR='/usr/bin/nvim'
export MANPAGER='/usr/bin/nvim +Man!'
export PAGER='/usr/bin/less'
export VISUAL='/usr/bin/nvim'
export FZF_DEFAULT_OPTS_FILE="${XDG_CONFIG_HOME}/fzf/fzfrc"
export RIPGREP_CONFIG_PATH="${XDG_CONFIG_HOME}/ripgrep/ripgreprc"
