# ------------------------------------------------------------------------------
# VARIABLES
# ------------------------------------------------------------------------------
set $font Terminess Nerd Font Mono bold 12

set $gap_in 10
set $gap_out_h -10
set $gap_out_v -5

set $win_border 2
set $win_float_max 1200 x 600
set $win_float_min 800 x 400
# ------------------------------------------------------------------------------
# CONFIG
# ------------------------------------------------------------------------------
# Font for window titles.
font pango:$font

# Set title bar border size and visibility
default_border pixel $win_border
#default_border normal $win_border

# Set the window title's text alignment
title_align center

# Set inner and outer gaps size
gaps inner $gap_in
gaps vertical $gap_out_v
gaps horizontal $gap_out_h

# When a client requests window activation, the window will become focused
# focus_on_window_activation focus

# Set colors for windows elements
# class                 border  background text    indicator child border
client.focused          #ffffff #0000aa    #ffffff #0000aa   #ffffff
client.focused_inactive #ffffff #0000aa    #ffffff #0000aa   #ffffff
client.unfocused        #aaaaaa #555555    #aaaaaa #555555   #555555
client.urgent           #aa0000 #aa0000    #ffffff #ff5555   #ff5555

client.background       #ffffff

# Constrain floating window size
floating_maximum_size $win_float_max
floating_minimum_size $win_float_min
