# ------------------------------------------------------------------------------
# VARIABLES
# ------------------------------------------------------------------------------
# Window resize step
set $win_resize_h 5px
set $win_resize_w 10px
# ------------------------------------------------------------------------------
# CONFIG
# ------------------------------------------------------------------------------
# Resize window (you can also use the mouse for that)
mode "resize" {
  # These bindings trigger as soon as you enter the resize mode

  # Pressing left will shrink the window’s width.
  # Pressing right will grow the window’s width.
  # Pressing up will shrink the window’s height.
  # Pressing down will grow the window’s height.
  bindsym Left resize shrink width $win_resize_w
  bindsym Down resize grow height $win_resize_h
  bindsym Up resize shrink height $win_resize_h
  bindsym Right resize grow width $win_resize_w

  # Back to normal: Enter or Escape
  bindsym Return mode "default"
  bindsym Escape mode "default"
}
