# Notification daemon
# exec dunst

# Set the wallpaper
#exec feh --bg-scale --no-fehbg $WALLPAPER

# Status bar
# exec_always ${HOME}/.config/polybar/polybar-start

# Removable disk mounter
# exec udiskie

# xss-lock grabs a logind suspend inhibit lock and will use i3lock to lock the
# screen before suspend. Use loginctl lock-session to lock your screen.
# exec xss-lock --transfer-sleep-lock "${HOME}/.config/i3lock-color/i3lock-start"
