#!/bin/sh

BG_COLOR=000000ff
GREETER='SCREEN LOCKED'
DATE='%d/%m/%Y'
TIME='%H:%M:%S'
POS_GREETER="w/2:10*h/24"
POS_DATE="w/2:h/2"
POS_TIME="w/2:10*h/18"
TEXT_FONT='Terminess Nerd Font Mono'
TEXT_SIZE=32
TEXT_COLOR='#FFFFFF'

i3lock --ignore-empty-password \
  --nofork \
  --no-unlock-indicator \
  --color="${BG_COLOR}" \
  --clock \
  --greeter-text="${GREETER}" --greeter-pos="${POS_GREETER}" --greeter-font="${TEXT_FONT}" --greeter-size="${TEXT_SIZE}" --greeter-color="${TEXT_COLOR}" \
  --date-str="${DATE}" --date-pos="${POS_DATE}" --date-font="${TEXT_FONT}" --date-size="${TEXT_SIZE}" --date-color="${TEXT_COLOR}" \
  --time-str="${TIME}" --time-pos="${POS_TIME}" --time-font="${TEXT_FONT}" --time-size="${TEXT_SIZE}" --time-color="${TEXT_COLOR}" \
