# OSD
osd-font="IBMVGA Nerd Font Mono"
sub-font="IBMVGA Nerd Font Mono"
sub-ass-override=yes
sub-ass-style-overrides=FontName="IBMVGA Nerd Font Mono"

# Audio and subtitles
alang=jpn,en,pt-BR
slang=en,pt-BR

# Screenshot
screenshot-directory="~/Media"
screenshot-template="%F-%n-%p"
screenshot-format=png
