#!/bin/sh

# This is a wrapper script for lf that allows it to create image previews with
# ueberzug. This works in concert with the lf configuration file and the
# lf-cleaner script.
set -e

LF_CACHE="${XDG_CACHE_HOME:-${HOME}/.cache}/lf"
UB_PID=0
UB_SOCKET=""
UB_TMP_DIR="/tmp"

cleanup() {
  exec 3>&-
  ueberzugpp cmd -s "${UB_SOCKET}" -a exit
}

[ ! -d "${LF_CACHE}" ] && mkdir -p "${LF_CACHE}"
UB_PID_FILE="${UB_TMP_DIR}/.$(uuidgen)"
ueberzugpp layer --no-cache --silent --no-stdin --use-escape-codes \
  --pid-file "${UB_PID_FILE}"
UB_PID=$(cat "${UB_PID_FILE}")
rm "${UB_PID_FILE}"
UB_SOCKET="${UB_TMP_DIR}/ueberzugpp-${UB_PID}.socket"
export UB_PID UB_SOCKET
trap cleanup HUP INT QUIT TERM EXIT
lf "$@" 3>&-
