#!/bin/sh

userresources="${HOME}"/.Xresources
usermodmap="${HOME}"/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps
[ -f "${sysresources}" ] && xrdb -merge $sysresources
[ -f "${sysmodmap}" ] && xmodmap "${sysmodmap}"
[ -f "${userresources}" ] && xrdb -merge "${userresources}"
[ -f "${usermodmap}" ] && xmodmap "${usermodmap}"

# start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
    [ -x "$f" ] && . "$f"
  done

  unset f
fi

# load local Xresources
xrdb -load "${HOME}"/.config/X11/xresources

# start the i3 window manager
export XDG_SESSION_TYPE=x11
export XDG_CURRENT_DESKTOP=i3
export TERM=alacritty
exec i3
