#!/bin/sh

OPT_TURNON_ALL=3
OPT_TURNON_LIBVIRTD=1
OPT_TURNON_SMB=2
OPT_TURNOFF_ALL=6
OPT_TURNOFF_LIBVIRTD=4
OPT_TURNOFF_SMB=5

printf "SERVICES\n\
%s) Start libvirtd\n\
%s) Start smb\n\
%s) Start both\n\
%s) Stop libvirtd\n\
%s) Stop smb\n\
%s) Stop both\n\n" \
"${OPT_TURNON_LIBVIRTD}" \
"${OPT_TURNON_SMB}" \
"${OPT_TURNON_ALL}" \
"${OPT_TURNOFF_LIBVIRTD}" \
"${OPT_TURNOFF_SMB}" \
"${OPT_TURNOFF_ALL}"

printf "Option: "
read -r option

case "${option}" in
  "${OPT_TURNON_LIBVIRTD}") systemctl start libvirtd ;;
  "${OPT_TURNON_SMB}") systemctl start smb ;;
  "${OPT_TURNON_ALL}") systemctl start libvirtd smb ;;
  "${OPT_TURNOFF_LIBVIRTD}") systemctl stop libvirtd* ;;
  "${OPT_TURNOFF_SMB}") systemctl stop smb ;;
  "${OPT_TURNOFF_ALL}") systemctl stop libvirtd smb;;
  *) exit 1 ;;
esac

exit 0
