# Alacritty documentation:
# https://alacritty.org/config-alacritty.html

[general]
#import = ["<string>",]
# Import additional configuration files.
# Imports are loaded in order, skipping all missing files, with the importing
# file being loaded last. If a field is already present in a previous import, it
# will be replaced.
# All imports must either be absolute paths starting with /, paths relative to
# the user's home directory starting with ~/, or paths relative from the current
# config file.
import = ["~/.config/alacritty/themes/maozinha23.toml",]

[window]
#padding = { x = <integer>, y = <integer> }
# Blank space added around the window in pixels. This padding is scaled by DPI
# and the specified value is always added at both opposing sides.
# Default: { x = 0, y = 0 }
padding = { x = 5, y = 5 }

[font]
#normal = { family = "<string>", style = "<string>" }
# Default:
#     Linux/BSD: { family = "monospace", style = "Regular" }
normal = { family = "Terminess Nerd Font Mono", style = "Regular" }

#size = <float>
# Font size in points.
# Default: 11.25
size = 11.25

[cursor]
# style = { <shape>, <blinking> }
# shape = "Block" | "Underline" | "Beam"
# Default: "Block"
#
# blinking = "Never" | "Off" | "On" | "Always"
#     Never
#         Prevent the cursor from ever blinking
#     Off
#         Disable blinking by default
#     On
#         Enable blinking by default
#     Always
#         Force the cursor to always blink
#     Default: "Off"
style = { shape = "Block", blinking = "On" }

[mouse]
#hide_when_typing = true | false
# When this is true, the cursor is temporarily hidden when typing.
# Default: false
hide_when_typing = true
