# ------------------------------------------------------------------------------
# VARIABLES
# ------------------------------------------------------------------------------
set $font IBM VGA Nerd Font Mono 16

set $gap_in 10
set $gap_out_bottom -10
set $gap_out_h -10
set $gap_out_top 38

set $win_border 2
set $win_float_max 1200 x 600
set $win_float_min 800 x 400

set $gnome-schema org.gnome.desktop.interface
# ------------------------------------------------------------------------------
# CONFIG
# ------------------------------------------------------------------------------
# Font for window titles
font pango:$font

# Set window border size and visibility
default_border pixel $win_border

# Set the window title's text alignment
title_align center

# Set inner and outer gaps size
gaps inner $gap_in
gaps top $gap_out_top
gaps bottom $gap_out_bottom
gaps horizontal $gap_out_h

# Set colors for windows elements
# class                  border  background text    indicator child border
client.background                #aaaaaa
client.focused           #aaaaaa #0000aa    #aaaaaa #00aaaa   #aaaaaa
client.focused_inactive  #555555 #0000aa    #aaaaaa #555555   #555555
client.focused_tab_title #aaaaaa #0000aa    #aaaaaa
client.unfocused         #555555 #555555    #aaaaaa #555555   #555555
client.urgent            #aa0000 #aa0000    #aaaaaa #aa0000   #aa0000

# Constrain floating window size
floating_maximum_size $win_float_max
floating_minimum_size $win_float_min

# GTK settings
# exec_always {
  # gsettings set $gnome-schema gtk-theme 'theme'
  # gsettings set $gnome-schema icon-theme 'icon'
  # gsettings set $gnome-schema cursor-theme 'cursor'
  # gsettings set $gnome-schema font-name 'IBMVGA Nerd Font Mono 14'
# }
