# ------------------------------------------------------------------------------
# VARIABLES
# ------------------------------------------------------------------------------
# Window move and resize step
set $win_move_h 10px
set $win_move_v 5px
set $win_resize_h 5px
set $win_resize_w 10px
# ------------------------------------------------------------------------------
# CONFIG
# ------------------------------------------------------------------------------
# Move window (you can also use the mouse for that)
mode "move" {
  # Move the window horizontally
  bindsym Left move left $win_move_h
  bindsym Right move right $win_move_h
  # Move the window vertically
  bindsym Down move down $win_move_v
  bindsym Up move up $win_move_v

  # Back to normal
  bindsym Return mode "default"
  bindsym Escape mode "default"
  bindsym $mod+m mode "default"
}

# Resize window (you can also use the mouse for that)
mode "resize" {
  # Grow/shrink the window’s height
  bindsym Down resize grow height $win_resize_h
  bindsym Up resize shrink height $win_resize_h
  # Grow/shrink the window’s width
  bindsym Left resize shrink width $win_resize_w
  bindsym Right resize grow width $win_resize_w

  # Back to normal
  bindsym Return mode "default"
  bindsym Escape mode "default"
  bindsym $mod+r mode "default"
}
