# ------------------------------------------------------------------------------
# VARIABLES
# ------------------------------------------------------------------------------
set $output_hdmi HDMI-A-1
set $output_lvds LVDS-1
set $output_vga VGA-1
# ------------------------------------------------------------------------------
# CONFIG
# ------------------------------------------------------------------------------
# Assign displays -> workspaces
# LVDS
workspace 1 output $output_lvds
workspace 2 output $output_lvds
workspace 3 output $output_lvds
workspace 4 output $output_lvds
workspace 5 output $output_lvds
# HDMI
workspace 6 output $output_hdmi
# VGA
workspace 6 output $output_vga

# Assign applications -> workspaces
# Workspace 1
for_window [app_id=foot title=^download$] move container to workspace 1, focus
for_window [app_id=foot title=^foot$] move container to workspace 1, focus
for_window [app_id=foot title=^qalc$] move container to workspace 1, focus
for_window [app_id=foot title=^nvim$] move container to workspace 1, focus
# Workspace 2
for_window [app_id=firefox] move container to workspace 2, focus
# Workspace 3
for_window [app_id=mpv] move container to workspace 3, focus
for_window [app_id=swayimg] move container to workspace 3, focus
# Workspace 4
for_window [app_id=Pinta] move container to workspace 4, focus
for_window [app_id=libreoffice] move container to workspace 4, focus
# Workspace 5
for_window [app_id=foot title=^bluetui$] move container to workspace 5, focus
for_window [app_id=foot title=^brightness$] move container to workspace 5, focus
for_window [app_id=foot title=^btop$] move container to workspace 5, focus
for_window [app_id=foot title=^font-viewer$] move container to workspace 5, focus
for_window [app_id=foot title=^lf$] move container to workspace 5, focus
for_window [app_id=localsend] move container to workspace 5, focus
for_window [app_id=foot title=^ncdu$] move container to workspace 5, focus
for_window [app_id=foot title=^nmtui$] move container to workspace 5, focus
for_window [app_id=foot title=^pacman$] move container to workspace 5, focus
for_window [app_id=foot title=^pulsemixer$] move container to workspace 5, focus
